import {
    AboutDataType,
    AboutReportDataType,
    AboutReportTranslateDataType,
    AboutTranslateDataType,
    BannerDataType,
    BannerTranslateDataType,
    CareerDataType,
    CareerTranslateDataType,
    CustomerDataType,
    EventDataType,
    EventGalleryDataType,
    EventTranslateDataType,
    FaqDataType,
    FaqTranslateDataType,
    GalleryDataType,
    MenuDataType,
    MenuTranslateDataType,
    NewsDataType,
    NewsTranslateDataType,
    PartnerDataType,
    ReportDataType,
    ReportTranslateDataType,
    SettingDataType,
    SettingTranslateDataType,
    TrainerDataType,
    TrainerTranslateDataType,
    TrainingCategoryDataType,
    TrainingCategoryTranslateDataType,
    TrainingDataType,
    TrainingTranslateDataType,
} from './data';

import {
    LocaleStateType,
    RootStateType,
    SearchStateType,
} from './redux'

import {
    RootLayoutType,
    HomeLayoutType,
    AboutLayoutType,
    CareerPageLayoutType,
    VacancyPageLayoutType,
    ContactPageLayoutType,
    EventPageLayoutType,
    EventInnerPageLayoutType,
    FaqPageLayoutType,
    NewsPageLayoutType,
    NewsInnerPageLayoutType,
    SearchPageLayoutType,
    TrainerPageLayoutType,
    TrainingPageLayoutType,
    CategoryPageLayoutType,
    TrainingInnerPageLayoutType,
} from './layout'

import {
    FooterProps,
    HeaderProps,
    MenuProps,
    SearchProps,
} from './partials'

import {
    ApplyCanvasProps,
    BannerSlideProps,
    Breadcrumb,
    CategoryCardContentProps,
    CounterProps,
    EventCardProps,
    LanguageProps,
    MenuLinkProps,
    NewsCardProps,
    PageTitleProps,
    PhotoGalleryProps,
    PopularTrainingCardProps,
    ReportItemProps,
    SectionTitleProps,
    SiteToolbarProps,
    SocialMediaProps,
    TrainerCardProps,
    TrainingAccordionProps,
    TrainingCanvasProps,
    TrainingCardContentCardProps,
    TrainingCardProps,
    TrainingModalProps,
    TrainingModelContentContentProps,
    VideoGalleryProps
} from './component'

import {
    AccordionFormContainerProps,
    ApplyContainerProps,
    ApplyFormValues,
    ContactFormProps,
    ContactFormValues,
    FileControlProps,
    FormControlProps,
    InputControlProps,
    SelectControlProps,
    TextareaControlProps,
    VacancyFormValues,
    VacanyFormContainerProps,
} from './form'

import {
    AboutSectionProps,
    ApplySectionProps,
    BannerSectionProps,
    CareerSectionProps,
    CategoryInnerSectionProps,
    ContactSectionProps,
    CustomerSectionProps,
    EventInnerSectionProps,
    EventSectionProps,
    FaqSectionProps,
    GallerySectionProps,
    NewsInnerSectionProps,
    NewsSectionProps,
    OtherTrainingSectionProps,
    PartnerSectionProps,
    ReportSectionProps,
    SearchSectionProps,
    Section404Props,
    TrainerInnerSectionProps,
    TrainerSectionProps,
    TrainingHomeSectionProps,
    TrainingInnerSectionProps,
    TrainingPageSectionProps,
    VacanySectionProps,
} from './section'

export type {
    AboutDataType,
    AboutReportDataType,
    AboutReportTranslateDataType,
    AboutTranslateDataType,
    BannerDataType,
    BannerTranslateDataType,
    CareerDataType,
    CareerTranslateDataType,
    CustomerDataType,
    EventDataType,
    EventGalleryDataType,
    EventTranslateDataType,
    FaqDataType,
    FaqTranslateDataType,
    GalleryDataType,
    MenuDataType,
    MenuTranslateDataType,
    NewsDataType,
    NewsTranslateDataType,
    PartnerDataType,
    ReportDataType,
    ReportTranslateDataType,
    SettingDataType,
    SettingTranslateDataType,
    TrainerDataType,
    TrainerTranslateDataType,
    TrainingCategoryDataType,
    TrainingCategoryTranslateDataType,
    TrainingDataType,
    TrainingTranslateDataType,
    LocaleStateType,
    RootStateType,
    SearchStateType,
    TrainingPageLayoutType,

    RootLayoutType,
    HomeLayoutType,
    AboutLayoutType,
    CareerPageLayoutType,
    VacancyPageLayoutType,
    ContactPageLayoutType,
    EventPageLayoutType,
    EventInnerPageLayoutType,
    FaqPageLayoutType,
    NewsPageLayoutType,
    NewsInnerPageLayoutType,
    SearchPageLayoutType,
    TrainerPageLayoutType,
    CategoryPageLayoutType,
    TrainingInnerPageLayoutType,


    FooterProps,
    HeaderProps,
    MenuProps,
    SearchProps,
    ApplyCanvasProps,
    BannerSlideProps,
    Breadcrumb,
    CategoryCardContentProps,
    CounterProps,
    EventCardProps,
    LanguageProps,
    MenuLinkProps,
    NewsCardProps,
    PageTitleProps,
    PhotoGalleryProps,
    PopularTrainingCardProps,
    ReportItemProps,
    SectionTitleProps,
    SiteToolbarProps,
    SocialMediaProps,
    TrainerCardProps,
    TrainingAccordionProps,
    TrainingCanvasProps,
    TrainingCardContentCardProps,
    TrainingCardProps,
    TrainingModalProps,
    TrainingModelContentContentProps,
    VideoGalleryProps,
    AccordionFormContainerProps,
    ApplyContainerProps,
    ApplyFormValues,
    ContactFormProps,
    ContactFormValues,
    FileControlProps,
    FormControlProps,
    InputControlProps,
    SelectControlProps,
    TextareaControlProps,
    VacancyFormValues,
    VacanyFormContainerProps,
    AboutSectionProps,
    ApplySectionProps,
    BannerSectionProps,
    CareerSectionProps,
    CategoryInnerSectionProps,
    ContactSectionProps,
    CustomerSectionProps,
    EventInnerSectionProps,
    EventSectionProps,
    FaqSectionProps,
    GallerySectionProps,
    NewsInnerSectionProps,
    NewsSectionProps,
    OtherTrainingSectionProps,
    PartnerSectionProps,
    ReportSectionProps,
    SearchSectionProps,
    Section404Props,
    TrainerInnerSectionProps,
    TrainerSectionProps,
    TrainingHomeSectionProps,
    TrainingInnerSectionProps,
    TrainingPageSectionProps,
    VacanySectionProps,
}