// data fetch
import {
    fetchSetting,
    fetchSettingTranslate,
    fetchMenu, 
    fetchMenuTranslate,
    fetchBanner,
    fetchBannerTranslate,
    fetchReport,
    fetchReportTranslate,
    fetchAbout,
    fetchAboutTranslate,
    fetchAboutReport,
    fetchAboutReportTranslate,
    fetchTrainingCategory,
    fetchTrainingCategoryTranslate,
    fetchTraining,
    fetchTrainingTranslate,
    fetchTrainer,
    fetchTrainerTranslate,
    fetchEvent,
    fetchEventTranslate,
    fetchEventGallery,
    fetchNews,
    fetchNewsTranslate,
    fetchGallery,
    fetchCustomer,
    fetchPartner,
    fetchFaq,
    fetchFaqTranslate,
    fetchCareer,
    fetchCareerTranslate,
} from './dataFetching';
// slider settings
import {
    bannerSettings,
    trainingCategorySettings,
    trainingModalSliderSettings,
    trainerSliderettings,
    otherTrainingSliderSettings,
    eventHomeSliderSettings,
    eventGallerySliderSettings,
    otherEventsSliderSettings,
    newsSliderSettings,
    customerSliderSettings,
    partnerSliderSettings
} from './sliderSetting'


export {
    fetchSetting,
    fetchSettingTranslate,
    fetchMenu, 
    fetchMenuTranslate,
    fetchBanner,
    fetchBannerTranslate,
    fetchReport,
    fetchReportTranslate,
    fetchAbout,
    fetchAboutTranslate,
    fetchAboutReport,
    fetchAboutReportTranslate,
    fetchTrainingCategory,
    fetchTrainingCategoryTranslate,
    fetchTraining,
    fetchTrainingTranslate,
    fetchTrainer,
    fetchTrainerTranslate,
    fetchEvent,
    fetchEventTranslate,
    fetchEventGallery,
    fetchNews,
    fetchNewsTranslate,
    fetchGallery,
    fetchCustomer,
    fetchPartner,
    fetchFaq,
    fetchFaqTranslate,
    fetchCareer,
    fetchCareerTranslate,

    bannerSettings,
    trainingCategorySettings,
    trainingModalSliderSettings,
    trainerSliderettings,
    otherTrainingSliderSettings,
    eventHomeSliderSettings,
    eventGallerySliderSettings,
    otherEventsSliderSettings,
    newsSliderSettings,
    customerSliderSettings,
    partnerSliderSettings,
}

